# PostgreSQL. Versions 9.1 and up are supported.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: riverfield
  host: localhost

development:
  <<: *default
  database: codr_development

test:
  <<: *default
  database: codr_test

production:
  <<: *default
  database: codr_production
  username: codr_ticket
  password: <%= ENV['CODR_DATABASE_PASSWORD'] %>
